name: Training
version: 1.0
api-version: 1.19
main: net.javamio.Training
author: JavaMio
website: https://github.com/MioArchive
description: A plugin which spawns a zombie for PvP Practice

commands:
  training:
    description: Main command to spawn the Zombie
    usage: '/training'
    permission: training.use
    default: op
    aliases: [practice, train]