name: Training
version: 1.0
api-version: 1.19
main: net.javamio.Training
authors:
  - JavaMio
  - Insolventer
website: https://github.com/MioArchive
description: A plugin which spawns a zombie for PvP Practice

commands:
  training:
    description: Main command to spawn the Zombie
    usage: '/training'
    aliases: [practice, train]